spring.application.name=weatherP01

spring.api.key = 8f5a5d5e51e64b2aac382948260301
spring.api.url = http://api.weatherapi.com/v1/current.json

spring.api.forecast.key = 8f5a5d5e51e64b2aac382948260301
spring.api.forecast.url = http://api.weatherapi.com/v1/forecast.json


