spring.application.name=clss

spring.datasource.url = jdbc:mysql://localhost:3306/class
spring.datasource.username = root
spring.datasource.password = Prince@ARMY13


spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
